import { Injectable } from '@nestjs/common';
import { SiteSettings } from '@builder/shared';

// Style preset configurations
interface StylePresetConfig {
  fontFamily: string;
  headingWeight: string;
  borderRadius: string;
  shadowIntensity: string;
  backgroundStyle: string;
  buttonStyle: string;
}

const STYLE_PRESETS: Record<string, StylePresetConfig> = {
  modern: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    headingWeight: '700',
    borderRadius: '12px',
    shadowIntensity: '0 10px 40px rgba(0,0,0,0.1)',
    backgroundStyle: 'gradient',
    buttonStyle: 'rounded-gradient',
  },
  classic: {
    fontFamily: "'Georgia', 'Times New Roman', serif",
    headingWeight: '600',
    borderRadius: '4px',
    shadowIntensity: '0 2px 8px rgba(0,0,0,0.08)',
    backgroundStyle: 'solid',
    buttonStyle: 'squared',
  },
  bold: {
    fontFamily: "'Poppins', 'Montserrat', sans-serif",
    headingWeight: '800',
    borderRadius: '0',
    shadowIntensity: '0 20px 60px rgba(0,0,0,0.15)',
    backgroundStyle: 'dark',
    buttonStyle: 'sharp',
  },
  minimal: {
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    headingWeight: '500',
    borderRadius: '2px',
    shadowIntensity: 'none',
    backgroundStyle: 'clean',
    buttonStyle: 'outline',
  },
  playful: {
    fontFamily: "'Nunito', 'Comic Sans MS', cursive",
    headingWeight: '700',
    borderRadius: '24px',
    shadowIntensity: '0 8px 30px rgba(0,0,0,0.12)',
    backgroundStyle: 'colorful',
    buttonStyle: 'pill',
  },
  professional: {
    fontFamily: "'Source Sans Pro', 'Open Sans', sans-serif",
    headingWeight: '600',
    borderRadius: '6px',
    shadowIntensity: '0 4px 16px rgba(0,0,0,0.06)',
    backgroundStyle: 'corporate',
    buttonStyle: 'standard',
  },
};

@Injectable()
export class StylesService {
  /**
   * Generate premium CSS for a WordPress site based on settings
   */
  generatePremiumCSS(settings: SiteSettings): string {
    const preset = STYLE_PRESETS[settings.stylePreset] || STYLE_PRESETS.modern;
    const accentColor = settings.accentColor || '#8B5CF6';
    const accentRGB = this.hexToRGB(accentColor);
    const accentDark = this.adjustColor(accentColor, -30);
    const accentLight = this.adjustColor(accentColor, 40);

    return `
/* =================================================================
   PREMIUM WEBSITE STYLES - Generated by AI Website Builder
   Professional 5-Page Website with Dark Mode & Animations
   ================================================================= */

/* Import Google Fonts */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Poppins:wght@300;400;500;600;700;800;900&family=Nunito:wght@400;600;700;800&family=Source+Sans+Pro:wght@300;400;600;700&family=Georgia&display=swap');

/* =================================================================
   CSS VARIABLES - Light & Dark Mode
   ================================================================= */
:root {
  /* Brand Colors */
  --accent-color: ${accentColor};
  --accent-dark: ${accentDark};
  --accent-light: ${accentLight};
  --accent-rgb: ${accentRGB};
  --accent-glow: rgba(${accentRGB}, 0.4);
  --accent-subtle: rgba(${accentRGB}, 0.1);
  --accent-medium: rgba(${accentRGB}, 0.2);

  /* Typography */
  --font-family: ${preset.fontFamily};
  --heading-weight: ${preset.headingWeight};
  --font-size-base: 17px;

  /* Spacing */
  --space-xs: 0.5rem;
  --space-sm: 1rem;
  --space-md: 2rem;
  --space-lg: 4rem;
  --space-xl: 6rem;
  --space-2xl: 8rem;

  /* Border & Shadow */
  --border-radius: ${preset.borderRadius};
  --border-radius-lg: calc(${preset.borderRadius} * 2);
  --border-radius-xl: calc(${preset.borderRadius} * 3);
  --shadow: ${preset.shadowIntensity};
  --shadow-lg: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
  --shadow-xl: 0 35px 60px -15px rgba(0, 0, 0, 0.3);
  --shadow-glow: 0 0 40px rgba(${accentRGB}, 0.15);
  --shadow-card: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1);
  --shadow-card-hover: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);

  /* Glassmorphism */
  --glass-bg: rgba(255, 255, 255, 0.7);
  --glass-border: rgba(255, 255, 255, 0.5);
  --glass-blur: 20px;

  /* Gradients */
  --gradient: linear-gradient(135deg, ${accentColor} 0%, ${accentDark} 100%);
  --gradient-reverse: linear-gradient(135deg, ${accentDark} 0%, ${accentColor} 100%);
  --gradient-subtle: linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%);
  --gradient-dark: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
  --gradient-mesh: radial-gradient(at 40% 20%, rgba(${accentRGB}, 0.15) 0px, transparent 50%),
                   radial-gradient(at 80% 0%, rgba(124, 58, 237, 0.12) 0px, transparent 50%),
                   radial-gradient(at 0% 50%, rgba(${accentRGB}, 0.1) 0px, transparent 50%),
                   radial-gradient(at 80% 50%, rgba(99, 102, 241, 0.08) 0px, transparent 50%),
                   radial-gradient(at 0% 100%, rgba(${accentRGB}, 0.1) 0px, transparent 50%);

  /* Light Mode Colors */
  --text-primary: #0f172a;
  --text-secondary: #475569;
  --text-muted: #94a3b8;
  --text-inverse: #ffffff;
  --background: #ffffff;
  --surface: #f8fafc;
  --surface-elevated: #ffffff;
  --border-color: rgba(0,0,0,0.08);

  /* Transitions */
  --transition-fast: 0.15s ease;
  --transition-normal: 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  --transition-slow: 0.5s cubic-bezier(0.4, 0, 0.2, 1);
  --transition-bounce: 0.5s cubic-bezier(0.34, 1.56, 0.64, 1);
}

/* Dark Mode */
[data-theme="dark"],
.dark-mode {
  --text-primary: #f8fafc;
  --text-secondary: #cbd5e1;
  --text-muted: #64748b;
  --text-inverse: #0f172a;
  --background: #0f172a;
  --surface: #1e293b;
  --surface-elevated: #334155;
  --border-color: rgba(255,255,255,0.1);
  --shadow: 0 10px 40px rgba(0,0,0,0.3);
  --gradient-subtle: linear-gradient(180deg, #1e293b 0%, #0f172a 100%);
  --glass-bg: rgba(30, 41, 59, 0.8);
  --glass-border: rgba(255, 255, 255, 0.1);
}

/* =================================================================
   BASE STYLES
   ================================================================= */
*, *::before, *::after {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: var(--font-family);
  font-size: var(--font-size-base);
  color: var(--text-primary);
  background-color: var(--background);
  line-height: 1.7;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}

/* =================================================================
   TYPOGRAPHY
   ================================================================= */
h1, h2, h3, h4, h5, h6,
.wp-block-heading {
  font-family: var(--font-family);
  font-weight: var(--heading-weight);
  line-height: 1.2;
  margin-bottom: 1rem;
  color: var(--text-primary);
  letter-spacing: -0.02em;
}

h1, .wp-block-heading[class*="h1"] {
  font-size: clamp(2.5rem, 6vw, 4.5rem);
}

h2, .wp-block-heading[class*="h2"] {
  font-size: clamp(2rem, 4vw, 3.25rem);
}

h3, .wp-block-heading[class*="h3"] {
  font-size: clamp(1.5rem, 3vw, 2rem);
}

h4, .wp-block-heading[class*="h4"] {
  font-size: clamp(1.25rem, 2.5vw, 1.5rem);
}

p {
  color: var(--text-secondary);
  margin-bottom: 1.5rem;
  font-size: 1.125rem;
  line-height: 1.8;
}

.lead, .has-large-font-size {
  font-size: 1.35rem;
  line-height: 1.7;
  color: var(--text-secondary);
}

.small, .has-small-font-size {
  font-size: 0.875rem;
  color: var(--text-muted);
}

a {
  color: var(--accent-color);
  text-decoration: none;
  transition: color var(--transition-fast);
}

a:hover {
  color: var(--accent-dark);
}

/* =================================================================
   LAYOUT & SECTIONS
   ================================================================= */
.wp-block-group {
  padding: var(--space-xl) var(--space-md);
  position: relative;
  overflow: hidden;
}

.section-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  position: relative;
  z-index: 2;
  width: 100%;
}

.wp-block-group > * {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}

/* Section Header - Premium centered heading group */
.section-header {
  text-align: center;
  max-width: 750px;
  margin: 0 auto var(--space-lg);
  position: relative;
}

.section-header::after {
  content: '';
  display: block;
  width: 60px;
  height: 4px;
  background: var(--gradient);
  border-radius: 2px;
  margin: var(--space-md) auto 0;
}

.section-header h2,
.section-header h3 {
  margin-bottom: var(--space-xs);
}

.section-header p {
  font-size: 1.2rem;
  color: var(--text-secondary);
  max-width: 600px;
  margin-left: auto;
  margin-right: auto;
}

/* Section Padding Variants */
.padding-none { padding: 0; }
.padding-sm { padding: var(--space-md) var(--space-sm); }
.padding-md { padding: var(--space-lg) var(--space-md); }
.padding-lg { padding: var(--space-xl) var(--space-md); }
.padding-xl { padding: var(--space-2xl) var(--space-md); }

/* =================================================================
   NAVIGATION
   ================================================================= */
.section-navigation {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;
  background: rgba(255,255,255,0.95);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border-bottom: 1px solid var(--border-color);
  padding: var(--space-sm) var(--space-md);
  transition: all var(--transition-normal);
}

.dark-mode .section-navigation {
  background: rgba(15,23,42,0.95);
}

.section-navigation .nav-container {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-navigation .logo {
  font-size: 1.5rem;
  font-weight: var(--heading-weight);
  color: var(--text-primary);
}

.section-navigation .nav-links {
  display: flex;
  gap: var(--space-md);
  list-style: none;
  margin: 0;
  padding: 0;
}

.section-navigation .nav-links a {
  color: var(--text-secondary);
  font-weight: 500;
  padding: var(--space-xs) var(--space-sm);
  border-radius: var(--border-radius);
  transition: all var(--transition-fast);
}

.section-navigation .nav-links a:hover,
.section-navigation .nav-links a.active {
  color: var(--accent-color);
  background: var(--accent-subtle);
}

/* Mobile Menu */
.mobile-menu-toggle {
  display: none;
  flex-direction: column;
  gap: 5px;
  cursor: pointer;
  padding: var(--space-xs);
}

.mobile-menu-toggle span {
  width: 24px;
  height: 2px;
  background: var(--text-primary);
  transition: all var(--transition-fast);
}

@media (max-width: 768px) {
  .mobile-menu-toggle {
    display: flex;
  }

  .section-navigation .nav-links {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    flex-direction: column;
    background: var(--surface);
    padding: var(--space-md);
    gap: var(--space-xs);
    display: none;
    border-bottom: 1px solid var(--border-color);
  }

  .section-navigation .nav-links.open {
    display: flex;
  }
}

/* =================================================================
   HERO SECTION - Premium Design with Gradient Mesh
   ================================================================= */
.section-hero {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--background);
  position: relative;
  overflow: hidden;
  padding: var(--space-2xl) var(--space-md);
  padding-top: calc(var(--space-2xl) + 80px);
}

/* Gradient mesh background */
.section-hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background: var(--gradient-mesh);
  z-index: 0;
}

/* Animated aurora blobs */
.hero-overlay {
  position: absolute;
  inset: 0;
  z-index: 1;
  overflow: hidden;
}

.hero-overlay::before {
  content: '';
  position: absolute;
  width: 800px;
  height: 800px;
  top: -300px;
  right: -200px;
  background: radial-gradient(circle, rgba(${accentRGB}, 0.3) 0%, rgba(${accentRGB}, 0.1) 40%, transparent 70%);
  border-radius: 50%;
  filter: blur(60px);
  animation: auroraFloat1 20s ease-in-out infinite;
}

.hero-overlay::after {
  content: '';
  position: absolute;
  width: 600px;
  height: 600px;
  bottom: -200px;
  left: -150px;
  background: radial-gradient(circle, rgba(124, 58, 237, 0.25) 0%, rgba(99, 102, 241, 0.1) 40%, transparent 70%);
  border-radius: 50%;
  filter: blur(50px);
  animation: auroraFloat2 25s ease-in-out infinite;
}

@keyframes auroraFloat1 {
  0%, 100% { transform: translate(0, 0) scale(1) rotate(0deg); }
  25% { transform: translate(-80px, 60px) scale(1.15) rotate(5deg); }
  50% { transform: translate(40px, -40px) scale(0.95) rotate(-3deg); }
  75% { transform: translate(60px, 80px) scale(1.1) rotate(3deg); }
}

@keyframes auroraFloat2 {
  0%, 100% { transform: translate(0, 0) scale(1) rotate(0deg); }
  33% { transform: translate(100px, -80px) scale(1.2) rotate(-5deg); }
  66% { transform: translate(-60px, 40px) scale(0.9) rotate(5deg); }
}

/* Third floating orb */
.section-hero > .section-container::before {
  content: '';
  position: absolute;
  width: 400px;
  height: 400px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: radial-gradient(circle, rgba(${accentRGB}, 0.08) 0%, transparent 60%);
  border-radius: 50%;
  filter: blur(40px);
  animation: pulseGlow 8s ease-in-out infinite;
  z-index: -1;
}

@keyframes pulseGlow {
  0%, 100% { transform: translate(-50%, -50%) scale(1); opacity: 0.5; }
  50% { transform: translate(-50%, -50%) scale(1.3); opacity: 0.8; }
}

.section-hero .section-container {
  display: flex;
  align-items: center;
  gap: var(--space-xl);
  position: relative;
  z-index: 3;
}

.hero-content {
  flex: 1;
  text-align: left;
}

/* Premium glassmorphism badge */
.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.625rem 1.5rem;
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  border: 1px solid var(--glass-border);
  border-radius: 100px;
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--accent-color);
  margin-bottom: var(--space-md);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.08);
  animation: slideInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.1s both;
}

.hero-badge::before {
  content: '';
  width: 8px;
  height: 8px;
  background: var(--gradient);
  border-radius: 50%;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { transform: scale(1); opacity: 1; }
  50% { transform: scale(1.2); opacity: 0.7; }
}

.section-hero h1 {
  font-size: clamp(3rem, 7vw, 5rem);
  max-width: 800px;
  margin-bottom: 1.5rem;
  position: relative;
  line-height: 1.05;
  letter-spacing: -0.04em;
  font-weight: 800;
  background: linear-gradient(135deg, var(--text-primary) 0%, var(--text-primary) 50%, var(--accent-color) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  animation: slideInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.2s both;
}

.section-hero .lead,
.section-hero p:not(.has-small-font-size) {
  font-size: clamp(1.125rem, 1.8vw, 1.375rem);
  max-width: 580px;
  margin: 0 0 2.5rem;
  color: var(--text-secondary);
  line-height: 1.75;
  animation: slideInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.3s both;
}

.hero-buttons {
  display: flex;
  gap: var(--space-sm);
  flex-wrap: wrap;
  animation: slideInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.4s both;
}

.hero-buttons .wp-block-button {
  margin: 0;
}

/* Premium hero visual with glassmorphism frame */
.hero-visual {
  flex: 1;
  position: relative;
  animation: slideInRight 1s cubic-bezier(0.16, 1, 0.3, 1) 0.4s both;
}

.hero-visual .wp-block-image {
  position: relative;
  border-radius: var(--border-radius-xl);
  overflow: hidden;
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  border: 1px solid var(--glass-border);
  padding: 12px;
  box-shadow:
    0 40px 100px rgba(0, 0, 0, 0.15),
    0 0 0 1px rgba(255, 255, 255, 0.1),
    var(--shadow-glow);
}

.hero-visual .wp-block-image::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(255,255,255,0.2) 0%, transparent 50%);
  border-radius: inherit;
  pointer-events: none;
}

.hero-visual .wp-block-image img {
  width: 100%;
  height: auto;
  display: block;
  border-radius: calc(var(--border-radius-xl) - 12px);
  transition: transform 0.8s cubic-bezier(0.16, 1, 0.3, 1);
}

.hero-visual .wp-block-image:hover img {
  transform: scale(1.05);
}

/* Floating accent shape behind hero image */
.hero-visual::before {
  content: '';
  position: absolute;
  width: 80%;
  height: 80%;
  bottom: -30px;
  right: -30px;
  background: var(--gradient);
  opacity: 0.15;
  border-radius: var(--border-radius-xl);
  z-index: -1;
  filter: blur(20px);
}

/* Hero background image (first image = background) */
.section-hero > .wp-block-image {
  position: absolute;
  inset: 0;
  z-index: 0;
  opacity: 0.05;
}

.section-hero > .wp-block-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  filter: blur(2px);
}

@media (max-width: 968px) {
  .section-hero .section-container {
    flex-direction: column;
    text-align: center;
  }
  .hero-content {
    text-align: center;
  }
  .hero-content h1,
  .hero-content p {
    max-width: 100%;
  }
  .hero-buttons {
    justify-content: center;
  }
  .hero-badge {
    margin-left: auto;
    margin-right: auto;
  }
}

/* =================================================================
   FEATURES SECTION - Premium Glassmorphism Cards
   ================================================================= */
.section-features {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
  position: relative;
  overflow: hidden;
}

/* Gradient mesh overlay */
.section-features::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse at 0% 0%, rgba(${accentRGB}, 0.08) 0%, transparent 50%),
    radial-gradient(ellipse at 100% 100%, rgba(124, 58, 237, 0.06) 0%, transparent 50%);
  pointer-events: none;
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: var(--space-md);
}

.features-grid .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
  margin: 0;
}

.section-features .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
  margin: 0;
}

/* Premium glassmorphism feature cards */
.section-features .wp-block-list li,
.features-grid .wp-block-list li {
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  padding: var(--space-lg);
  border-radius: var(--border-radius-xl);
  text-align: center;
  transition: all var(--transition-normal);
  border: 1px solid var(--glass-border);
  position: relative;
  overflow: hidden;
  box-shadow: var(--shadow-card);
}

/* Gradient shine overlay on cards */
.section-features .wp-block-list li::after,
.features-grid .wp-block-list li::after {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);
  transition: left 0.5s ease;
}

.section-features .wp-block-list li:hover,
.features-grid .wp-block-list li:hover {
  transform: translateY(-12px) scale(1.02);
  box-shadow: var(--shadow-card-hover), var(--shadow-glow);
  border-color: rgba(${accentRGB}, 0.3);
}

.section-features .wp-block-list li:hover::after,
.features-grid .wp-block-list li:hover::after {
  left: 100%;
}

/* Premium icon container */
.section-features .wp-block-list li::before,
.features-grid .wp-block-list li::before {
  content: '';
  display: block;
  width: 72px;
  height: 72px;
  margin: 0 auto var(--space-md);
  background: var(--gradient);
  border-radius: 20px;
  box-shadow: 0 8px 24px rgba(${accentRGB}, 0.3);
  position: relative;
  z-index: 1;
}

.section-features .wp-block-list li strong,
.features-grid .wp-block-list li strong {
  display: block;
  font-size: 1.35rem;
  margin-bottom: var(--space-sm);
  color: var(--text-primary);
  font-weight: var(--heading-weight);
}

/* =================================================================
   SERVICES SECTION - Premium Card Design
   ================================================================= */
.section-services {
  background: var(--background);
  padding: var(--space-xl) var(--space-md);
  position: relative;
  overflow: hidden;
}

/* Gradient mesh background */
.section-services::before {
  content: '';
  position: absolute;
  inset: 0;
  background:
    radial-gradient(ellipse at 100% 0%, rgba(${accentRGB}, 0.06) 0%, transparent 50%),
    radial-gradient(ellipse at 0% 100%, rgba(124, 58, 237, 0.05) 0%, transparent 50%);
  pointer-events: none;
}

.services-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
}

.services-grid .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
}

.section-services .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
}

/* Premium service cards with glassmorphism */
.section-services .wp-block-list li,
.services-grid .wp-block-list li {
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  padding: var(--space-lg);
  border-radius: var(--border-radius-xl);
  box-shadow: var(--shadow-card);
  transition: all var(--transition-normal);
  border: 1px solid var(--glass-border);
  position: relative;
  overflow: hidden;
}

/* Gradient top accent bar */
.section-services .wp-block-list li::before,
.services-grid .wp-block-list li::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 4px;
  background: var(--gradient);
  transform: scaleX(0);
  transform-origin: left;
  transition: transform var(--transition-normal);
}

/* Glow effect on hover */
.section-services .wp-block-list li::after,
.services-grid .wp-block-list li::after {
  content: '';
  position: absolute;
  inset: -2px;
  background: var(--gradient);
  border-radius: inherit;
  opacity: 0;
  z-index: -1;
  filter: blur(20px);
  transition: opacity var(--transition-normal);
}

.section-services .wp-block-list li:hover,
.services-grid .wp-block-list li:hover {
  transform: translateY(-12px);
  box-shadow: var(--shadow-xl), var(--shadow-glow);
  border-color: rgba(${accentRGB}, 0.3);
}

.section-services .wp-block-list li:hover::before,
.services-grid .wp-block-list li:hover::before {
  transform: scaleX(1);
}

.section-services .wp-block-list li:hover::after,
.services-grid .wp-block-list li:hover::after {
  opacity: 0.15;
}

.section-services .wp-block-list li strong,
.services-grid .wp-block-list li strong {
  display: block;
  font-size: 1.4rem;
  margin-bottom: var(--space-sm);
  color: var(--text-primary);
  font-weight: var(--heading-weight);
}

/* =================================================================
   TESTIMONIALS SECTION
   ================================================================= */
.section-testimonials {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
  position: relative;
}

.section-testimonials::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 1px;
  background: linear-gradient(90deg, transparent, var(--border-color), transparent);
}

.testimonials-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
}

.testimonials-grid .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
}

.section-testimonials .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
  gap: var(--space-md);
  list-style: none;
  padding: 0;
}

.section-testimonials .wp-block-list li,
.testimonials-grid .wp-block-list li {
  background: var(--surface-elevated);
  padding: var(--space-lg);
  border-radius: var(--border-radius-lg);
  position: relative;
  border: 1px solid var(--border-color);
  transition: all var(--transition-normal);
}

.section-testimonials .wp-block-list li:hover,
.testimonials-grid .wp-block-list li:hover {
  transform: translateY(-4px);
  box-shadow: 0 15px 40px rgba(0,0,0,0.08);
}

.section-testimonials .wp-block-list li::before,
.testimonials-grid .wp-block-list li::before {
  content: '"';
  font-size: 5rem;
  color: rgba(${accentRGB}, 0.15);
  position: absolute;
  top: var(--space-xs);
  left: var(--space-md);
  line-height: 1;
  font-family: Georgia, serif;
  font-weight: 700;
}

.section-testimonials .wp-block-list li p,
.testimonials-grid .wp-block-list li p {
  position: relative;
  z-index: 1;
  font-style: italic;
  margin-bottom: var(--space-md);
}

.section-testimonials .wp-block-list li strong,
.testimonials-grid .wp-block-list li strong {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
  color: var(--text-primary);
  font-weight: 600;
  font-size: 0.95rem;
  padding-top: var(--space-sm);
  border-top: 1px solid var(--border-color);
}

.section-testimonials .wp-block-list li strong::before,
.testimonials-grid .wp-block-list li strong::before {
  content: '';
  width: 44px;
  height: 44px;
  background: var(--gradient);
  border-radius: 50%;
  flex-shrink: 0;
  box-shadow: 0 4px 12px var(--accent-glow);
}

/* =================================================================
   ABOUT SECTION
   ================================================================= */
.section-about {
  background: var(--background);
  padding: var(--space-xl) var(--space-md);
  position: relative;
}

.about-layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-xl);
  align-items: center;
}

.about-image-col {
  position: relative;
}

.about-image-wrapper {
  position: relative;
}

.about-image-wrapper .wp-block-image {
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  box-shadow: 0 25px 60px rgba(0,0,0,0.12);
  position: relative;
  z-index: 2;
}

.about-image-wrapper .wp-block-image img {
  width: 100%;
  height: auto;
  display: block;
  transition: transform 0.5s ease;
}

.about-image-wrapper:hover .wp-block-image img {
  transform: scale(1.03);
}

.about-image-accent {
  position: absolute;
  bottom: -20px;
  right: -20px;
  width: 60%;
  height: 60%;
  background: var(--gradient);
  border-radius: var(--border-radius-lg);
  opacity: 0.15;
  z-index: 1;
}

.about-content-col h2,
.about-content-col h1 {
  text-align: left;
}

.about-content-col p {
  margin-bottom: 1.25rem;
}

.about-buttons {
  display: flex;
  gap: var(--space-sm);
  flex-wrap: wrap;
  margin-top: var(--space-md);
}

/* Fallback for about without image */
.section-about > .section-container > .section-header h2,
.section-about > .section-container > .section-header h1 {
  text-align: center;
}

.section-about .lead {
  text-align: center;
  max-width: 800px;
  margin: 0 auto var(--space-lg);
}

.section-about > .section-container > .wp-block-image {
  max-width: 900px;
  margin: var(--space-lg) auto;
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow-lg);
}

@media (max-width: 868px) {
  .about-layout {
    grid-template-columns: 1fr;
    gap: var(--space-lg);
  }
  .about-content-col h2,
  .about-content-col h1 {
    text-align: center;
  }
  .about-content-col p {
    text-align: center;
  }
  .about-buttons {
    justify-content: center;
  }
}

/* =================================================================
   TEAM SECTION
   ================================================================= */
.section-team {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
}

.section-team h2 {
  text-align: center;
  margin-bottom: var(--space-xs);
}

.section-team h2 + p {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-team .team-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: var(--space-md);
}

.section-team .team-member {
  background: var(--surface-elevated);
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  text-align: center;
  transition: all var(--transition-normal);
  border: 1px solid var(--border-color);
}

.section-team .team-member:hover {
  transform: translateY(-8px);
  box-shadow: var(--shadow-lg);
}

.section-team .team-member img {
  width: 100%;
  height: 300px;
  object-fit: cover;
}

.section-team .team-member-info {
  padding: var(--space-md);
}

.section-team .team-member-name {
  font-size: 1.35rem;
  font-weight: var(--heading-weight);
  color: var(--text-primary);
  margin-bottom: var(--space-xs);
}

.section-team .team-member-role {
  color: var(--accent-color);
  font-weight: 600;
  margin-bottom: var(--space-sm);
}

.section-team .team-member-bio {
  color: var(--text-muted);
  font-size: 0.95rem;
}

/* =================================================================
   TIMELINE SECTION
   ================================================================= */
.section-timeline {
  background: var(--background);
  padding: var(--space-xl) var(--space-md);
}

.section-timeline h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-timeline .timeline {
  position: relative;
  max-width: 800px;
  margin: 0 auto;
}

.section-timeline .timeline::before {
  content: '';
  position: absolute;
  left: 50%;
  top: 0;
  bottom: 0;
  width: 3px;
  background: var(--gradient);
  transform: translateX(-50%);
}

.section-timeline .timeline-item {
  position: relative;
  padding: var(--space-md);
  width: 50%;
  box-sizing: border-box;
}

.section-timeline .timeline-item:nth-child(odd) {
  padding-right: var(--space-lg);
  text-align: right;
}

.section-timeline .timeline-item:nth-child(even) {
  left: 50%;
  padding-left: var(--space-lg);
}

.section-timeline .timeline-item::before {
  content: '';
  position: absolute;
  width: 20px;
  height: 20px;
  background: var(--accent-color);
  border: 4px solid var(--background);
  border-radius: 50%;
  top: var(--space-md);
  box-shadow: 0 0 0 4px var(--accent-subtle);
}

.section-timeline .timeline-item:nth-child(odd)::before {
  right: -10px;
}

.section-timeline .timeline-item:nth-child(even)::before {
  left: -10px;
}

.section-timeline .timeline-year {
  font-size: 0.875rem;
  font-weight: 700;
  color: var(--accent-color);
  margin-bottom: var(--space-xs);
}

.section-timeline .timeline-title {
  font-size: 1.25rem;
  font-weight: var(--heading-weight);
  color: var(--text-primary);
  margin-bottom: var(--space-xs);
}

.section-timeline .timeline-description {
  color: var(--text-secondary);
  font-size: 0.95rem;
}

@media (max-width: 768px) {
  .section-timeline .timeline::before {
    left: 20px;
  }

  .section-timeline .timeline-item {
    width: 100%;
    padding-left: var(--space-lg) !important;
    padding-right: 0 !important;
    text-align: left !important;
  }

  .section-timeline .timeline-item:nth-child(even) {
    left: 0;
  }

  .section-timeline .timeline-item::before {
    left: 10px !important;
    right: auto !important;
  }
}

/* =================================================================
   STATS SECTION
   ================================================================= */
.section-stats {
  background: var(--gradient-dark);
  padding: var(--space-xl) var(--space-md);
  position: relative;
  overflow: hidden;
}

.section-stats::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -25%;
  width: 150%;
  height: 200%;
  background: radial-gradient(ellipse at center, rgba(${accentRGB}, 0.15) 0%, transparent 50%);
  pointer-events: none;
}

.section-stats .stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: var(--space-md);
  text-align: center;
  position: relative;
  z-index: 2;
}

.section-stats .stat-item {
  padding: var(--space-lg) var(--space-md);
  position: relative;
}

.section-stats .stat-item + .stat-item::before {
  content: '';
  position: absolute;
  top: 20%;
  left: 0;
  height: 60%;
  width: 1px;
  background: rgba(255,255,255,0.15);
}

.section-stats .stat-value {
  font-size: clamp(2.75rem, 5vw, 4rem);
  font-weight: 800;
  color: white;
  line-height: 1;
  margin-bottom: var(--space-xs);
  background: linear-gradient(135deg, white 30%, rgba(${accentRGB}, 0.7) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.section-stats .stat-label {
  font-size: 0.9rem;
  color: rgba(255,255,255,0.6);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-weight: 500;
}

/* =================================================================
   FAQ SECTION
   ================================================================= */
.section-faq {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
}

.section-faq h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-faq .faq-list {
  max-width: 800px;
  margin: 0 auto;
}

.section-faq .faq-item {
  background: var(--surface-elevated);
  margin-bottom: var(--space-sm);
  border-radius: var(--border-radius);
  overflow: hidden;
  border: 1px solid var(--border-color);
}

.section-faq .faq-question {
  padding: var(--space-md);
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 600;
  color: var(--text-primary);
  transition: all var(--transition-fast);
}

.section-faq .faq-question:hover {
  background: var(--accent-subtle);
  color: var(--accent-color);
}

.section-faq .faq-question::after {
  content: '+';
  font-size: 1.5rem;
  font-weight: 300;
  transition: transform var(--transition-fast);
}

.section-faq .faq-item.open .faq-question::after {
  transform: rotate(45deg);
}

.section-faq .faq-answer {
  padding: 0 var(--space-md) var(--space-md);
  color: var(--text-secondary);
  display: none;
}

.section-faq .faq-item.open .faq-answer {
  display: block;
  animation: slideDown 0.3s ease-out;
}

@keyframes slideDown {
  from { opacity: 0; transform: translateY(-10px); }
  to { opacity: 1; transform: translateY(0); }
}

/* =================================================================
   CONTACT SECTION
   ================================================================= */
.section-contact {
  background: var(--background);
  padding: var(--space-xl) var(--space-md);
}

.section-contact h2 {
  margin-bottom: var(--space-sm);
}

.section-contact .contact-info {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--space-md);
  margin-bottom: var(--space-lg);
}

.section-contact .contact-item {
  display: flex;
  align-items: center;
  gap: var(--space-sm);
}

.section-contact .contact-item::before {
  content: '';
  width: 48px;
  height: 48px;
  background: var(--accent-subtle);
  border-radius: var(--border-radius);
  flex-shrink: 0;
}

/* =================================================================
   CONTACT FORM SECTION
   ================================================================= */
.section-contactForm {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
}

.section-contactForm h2 {
  margin-bottom: var(--space-sm);
}

.section-contactForm form {
  max-width: 600px;
  margin: 0 auto;
}

.section-contactForm .form-group {
  margin-bottom: var(--space-md);
}

.section-contactForm label {
  display: block;
  margin-bottom: var(--space-xs);
  font-weight: 600;
  color: var(--text-primary);
}

.section-contactForm input,
.section-contactForm select,
.section-contactForm textarea {
  width: 100%;
  padding: var(--space-sm);
  border: 2px solid var(--border-color);
  border-radius: var(--border-radius);
  font-size: 1rem;
  font-family: var(--font-family);
  background: var(--surface-elevated);
  color: var(--text-primary);
  transition: all var(--transition-fast);
}

.section-contactForm input:focus,
.section-contactForm select:focus,
.section-contactForm textarea:focus {
  outline: none;
  border-color: var(--accent-color);
  box-shadow: 0 0 0 4px var(--accent-subtle);
}

.section-contactForm textarea {
  min-height: 150px;
  resize: vertical;
}

/* =================================================================
   MAP SECTION
   ================================================================= */
.section-map {
  background: var(--background);
  padding: var(--space-xl) var(--space-md);
}

.section-map h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-map .map-container {
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow);
}

.section-map iframe {
  width: 100%;
  height: 400px;
  border: none;
}

/* =================================================================
   BUSINESS HOURS SECTION
   ================================================================= */
.section-businessHours {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
}

.section-businessHours h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-businessHours .hours-table {
  max-width: 500px;
  margin: 0 auto;
  background: var(--surface-elevated);
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow);
}

.section-businessHours .hours-row {
  display: flex;
  justify-content: space-between;
  padding: var(--space-sm) var(--space-md);
  border-bottom: 1px solid var(--border-color);
}

.section-businessHours .hours-row:last-child {
  border-bottom: none;
}

.section-businessHours .hours-day {
  font-weight: 600;
  color: var(--text-primary);
}

.section-businessHours .hours-time {
  color: var(--text-secondary);
}

.section-businessHours .hours-closed {
  color: var(--text-muted);
}

/* =================================================================
   SOCIAL LINKS SECTION
   ================================================================= */
.section-socialLinks {
  background: var(--background);
  padding: var(--space-lg) var(--space-md);
}

.section-socialLinks h2 {
  text-align: center;
  margin-bottom: var(--space-md);
}

.section-socialLinks .social-icons {
  display: flex;
  justify-content: center;
  gap: var(--space-sm);
  flex-wrap: wrap;
}

.section-socialLinks .social-icon {
  width: 50px;
  height: 50px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--surface);
  border-radius: 50%;
  transition: all var(--transition-normal);
  border: 2px solid var(--border-color);
}

.section-socialLinks .social-icon:hover {
  background: var(--accent-color);
  border-color: var(--accent-color);
  transform: translateY(-4px);
}

.section-socialLinks .social-icon:hover svg,
.section-socialLinks .social-icon:hover i {
  color: white;
}

/* =================================================================
   CTA SECTION
   ================================================================= */
.section-cta {
  background: var(--gradient-dark);
  padding: var(--space-2xl) var(--space-md);
  text-align: center;
  position: relative;
  overflow: hidden;
}

.cta-pattern {
  position: absolute;
  inset: 0;
  background: radial-gradient(ellipse at 30% 50%, rgba(${accentRGB}, 0.25) 0%, transparent 50%),
              radial-gradient(ellipse at 70% 50%, rgba(${accentRGB}, 0.15) 0%, transparent 50%);
  z-index: 1;
}

.cta-content {
  position: relative;
  z-index: 2;
  max-width: 700px;
  margin: 0 auto;
}

.section-cta h2 {
  color: white;
  font-size: clamp(2rem, 4vw, 3rem);
}

.section-cta p,
.section-cta .lead {
  color: rgba(255,255,255,0.85);
  max-width: 600px;
  margin: 0 auto var(--space-md);
  font-size: 1.2rem;
}

.cta-buttons {
  display: flex;
  justify-content: center;
  gap: var(--space-sm);
  flex-wrap: wrap;
  margin-top: var(--space-md);
}

.section-cta .wp-block-button__link {
  background: white;
  color: var(--accent-color) !important;
  box-shadow: 0 4px 20px rgba(0,0,0,0.2);
}

.section-cta .wp-block-button__link:hover {
  background: var(--surface);
  transform: translateY(-3px);
  box-shadow: 0 8px 30px rgba(0,0,0,0.3);
}

/* =================================================================
   CONTACT LAYOUT
   ================================================================= */
.contact-layout {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-lg);
  align-items: start;
}

.contact-layout form {
  max-width: 100%;
}

@media (max-width: 768px) {
  .contact-layout {
    grid-template-columns: 1fr;
  }
}

/* =================================================================
   GALLERY SECTION
   ================================================================= */
.section-gallery {
  background: var(--surface);
  padding: var(--space-xl) var(--space-md);
}

.section-gallery h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-gallery .gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: var(--space-sm);
}

.section-gallery .gallery-item {
  aspect-ratio: 4/3;
  border-radius: var(--border-radius);
  overflow: hidden;
  cursor: pointer;
}

.section-gallery .gallery-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform var(--transition-slow);
}

.section-gallery .gallery-item:hover img {
  transform: scale(1.1);
}

/* =================================================================
   PRODUCTS/PRICING SECTION
   ================================================================= */
.section-products,
.section-pricing {
  background: var(--gradient-subtle);
  padding: var(--space-xl) var(--space-md);
}

.section-products h2,
.section-pricing h2 {
  text-align: center;
  margin-bottom: var(--space-lg);
}

.section-products .product-grid,
.section-pricing .pricing-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: var(--space-md);
}

.section-products .product-card,
.section-pricing .pricing-card {
  background: var(--surface-elevated);
  border-radius: var(--border-radius-lg);
  overflow: hidden;
  transition: all var(--transition-normal);
  border: 1px solid var(--border-color);
}

.section-products .product-card:hover,
.section-pricing .pricing-card:hover {
  transform: translateY(-8px);
  box-shadow: var(--shadow-lg);
}

.section-pricing .pricing-card.featured {
  border: 2px solid var(--accent-color);
  transform: scale(1.05);
}

.section-pricing .pricing-card.featured:hover {
  transform: scale(1.05) translateY(-8px);
}

.section-products .product-image {
  height: 200px;
  overflow: hidden;
}

.section-products .product-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform var(--transition-slow);
}

.section-products .product-card:hover .product-image img {
  transform: scale(1.1);
}

.section-products .product-info,
.section-pricing .pricing-info {
  padding: var(--space-md);
}

.section-products .product-title,
.section-pricing .pricing-title {
  font-size: 1.35rem;
  font-weight: var(--heading-weight);
  margin-bottom: var(--space-xs);
}

.section-products .product-price,
.section-pricing .pricing-price {
  font-size: 2rem;
  font-weight: 700;
  color: var(--accent-color);
  margin-bottom: var(--space-sm);
}

.section-pricing .pricing-features {
  list-style: none;
  padding: 0;
  margin: var(--space-md) 0;
}

.section-pricing .pricing-features li {
  padding: var(--space-xs) 0;
  border-bottom: 1px solid var(--border-color);
  display: flex;
  align-items: center;
  gap: var(--space-xs);
}

.section-pricing .pricing-features li::before {
  content: '✓';
  color: var(--accent-color);
  font-weight: bold;
}

/* =================================================================
   FOOTER SECTION
   ================================================================= */
.section-footer {
  background: var(--gradient-dark);
  color: white;
  padding: var(--space-xl) var(--space-md) var(--space-lg);
}

.section-footer .footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: var(--space-lg);
  margin-bottom: var(--space-lg);
}

.section-footer .footer-column h4 {
  color: white;
  margin-bottom: var(--space-md);
}

.section-footer .footer-column a {
  color: rgba(255,255,255,0.7);
  display: block;
  padding: var(--space-xs) 0;
  transition: all var(--transition-fast);
}

.section-footer .footer-column a:hover {
  color: white;
  padding-left: var(--space-xs);
}

.section-footer .footer-bottom {
  border-top: 1px solid rgba(255,255,255,0.1);
  padding-top: var(--space-md);
  text-align: center;
}

.section-footer .footer-bottom p,
.section-footer .footer-bottom small {
  color: rgba(255,255,255,0.5);
  margin: 0;
}

/* =================================================================
   BUTTONS - Premium Gradient with Glow Effects
   ================================================================= */
.wp-block-button {
  margin: var(--space-sm) 0;
}

.wp-block-button__link,
.wp-element-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 1rem 2rem;
  font-size: 1.05rem;
  font-weight: 600;
  letter-spacing: 0.01em;
  text-decoration: none;
  border-radius: var(--border-radius-lg);
  transition: all var(--transition-normal);
  cursor: pointer;
  border: none;
  background: var(--gradient);
  color: white !important;
  box-shadow:
    0 4px 15px rgba(${accentRGB}, 0.4),
    0 2px 4px rgba(0, 0, 0, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.15);
  position: relative;
  overflow: hidden;
  z-index: 1;
}

/* Glossy shine overlay */
.wp-block-button__link::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(180deg, rgba(255,255,255,0.15) 0%, transparent 50%);
  pointer-events: none;
}

/* Hover glow effect */
.wp-block-button__link::after {
  content: '';
  position: absolute;
  inset: -4px;
  background: var(--gradient);
  border-radius: inherit;
  z-index: -1;
  opacity: 0;
  filter: blur(16px);
  transition: opacity var(--transition-normal);
}

.wp-block-button__link:hover {
  transform: translateY(-4px) scale(1.02);
  box-shadow:
    0 12px 35px rgba(${accentRGB}, 0.5),
    0 4px 8px rgba(0, 0, 0, 0.15),
    inset 0 1px 0 rgba(255, 255, 255, 0.2);
}

.wp-block-button__link:hover::after {
  opacity: 0.6;
}

.wp-block-button__link:active {
  transform: translateY(-2px) scale(1);
}

/* Button Sizes */
.wp-block-button.size-sm .wp-block-button__link {
  padding: 0.625rem 1.25rem;
  font-size: 0.9rem;
  border-radius: var(--border-radius);
}

.wp-block-button.size-lg .wp-block-button__link {
  padding: 1.25rem 2.5rem;
  font-size: 1.2rem;
  border-radius: calc(var(--border-radius-lg) * 1.2);
}

/* Button Variants - Premium Outline */
.wp-block-button.is-style-outline .wp-block-button__link {
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  border: 2px solid var(--accent-color);
  color: var(--accent-color) !important;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
}

.wp-block-button.is-style-outline .wp-block-button__link::before {
  background: none;
}

.wp-block-button.is-style-outline .wp-block-button__link:hover {
  background: var(--gradient);
  color: white !important;
  border-color: transparent;
  box-shadow: 0 12px 35px rgba(${accentRGB}, 0.4);
}

/* Secondary button style */
.wp-block-button.is-style-secondary .wp-block-button__link {
  background: var(--glass-bg);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  color: var(--text-primary) !important;
  border: 1px solid var(--border-color);
  box-shadow: var(--shadow-card);
}

.wp-block-button.is-style-secondary .wp-block-button__link:hover {
  background: var(--surface);
  box-shadow: var(--shadow-card-hover);
  border-color: rgba(${accentRGB}, 0.2);
}

/* =================================================================
   IMAGES
   ================================================================= */
.wp-block-image {
  margin: var(--space-md) 0;
}

.wp-block-image img {
  max-width: 100%;
  height: auto;
  border-radius: var(--border-radius);
}

.wp-block-image.alignfull img {
  border-radius: 0;
}

.wp-block-image.has-shadow img {
  box-shadow: var(--shadow-lg);
}

/* =================================================================
   ANIMATIONS
   ================================================================= */
@keyframes slideInUp {
  from {
    opacity: 0;
    transform: translateY(40px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes slideInLeft {
  from {
    opacity: 0;
    transform: translateX(-40px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes slideInRight {
  from {
    opacity: 0;
    transform: translateX(40px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

@keyframes scaleIn {
  from {
    opacity: 0;
    transform: scale(0.95);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

/* Animate on scroll */
.animate-on-scroll {
  opacity: 0;
  transform: translateY(30px);
  transition: all 0.6s ease-out;
}

.animate-on-scroll.in-view {
  opacity: 1;
  transform: translateY(0);
}

/* Staggered animations for section content */
.section-header { animation: slideInUp 0.6s ease-out 0.1s both; }

.features-grid > *:nth-child(1),
.services-grid > *:nth-child(1),
.testimonials-grid > *:nth-child(1),
.pricing-grid > *:nth-child(1) { animation: slideInUp 0.5s ease-out 0.2s both; }

.features-grid > *:nth-child(2),
.services-grid > *:nth-child(2),
.testimonials-grid > *:nth-child(2),
.pricing-grid > *:nth-child(2) { animation: slideInUp 0.5s ease-out 0.3s both; }

.features-grid > *:nth-child(3),
.services-grid > *:nth-child(3),
.testimonials-grid > *:nth-child(3),
.pricing-grid > *:nth-child(3) { animation: slideInUp 0.5s ease-out 0.4s both; }

.about-image-col { animation: slideInLeft 0.7s ease-out 0.2s both; }
.about-content-col { animation: slideInRight 0.7s ease-out 0.3s both; }

.team-grid > *:nth-child(1) { animation: scaleIn 0.5s ease-out 0.2s both; }
.team-grid > *:nth-child(2) { animation: scaleIn 0.5s ease-out 0.3s both; }
.team-grid > *:nth-child(3) { animation: scaleIn 0.5s ease-out 0.4s both; }
.team-grid > *:nth-child(4) { animation: scaleIn 0.5s ease-out 0.5s both; }

.stats-grid > *:nth-child(1) { animation: slideInUp 0.5s ease-out 0.1s both; }
.stats-grid > *:nth-child(2) { animation: slideInUp 0.5s ease-out 0.2s both; }
.stats-grid > *:nth-child(3) { animation: slideInUp 0.5s ease-out 0.3s both; }
.stats-grid > *:nth-child(4) { animation: slideInUp 0.5s ease-out 0.4s both; }

/* =================================================================
   RESPONSIVE DESIGN
   ================================================================= */
@media (max-width: 1024px) {
  :root {
    --space-xl: 5rem;
    --space-2xl: 6rem;
  }
}

@media (max-width: 768px) {
  :root {
    --space-xl: 4rem;
    --space-2xl: 5rem;
  }

  .section-hero {
    min-height: 85vh;
    padding-top: calc(var(--space-xl) + 60px);
  }

  .section-hero h1 {
    font-size: clamp(2rem, 8vw, 3rem);
  }

  .section-hero .section-container {
    flex-direction: column;
    text-align: center;
  }

  .hero-content {
    text-align: center;
  }

  .hero-content p,
  .hero-content h1 {
    max-width: 100%;
  }

  .hero-buttons {
    justify-content: center;
  }

  .hero-badge {
    margin-left: auto;
    margin-right: auto;
  }

  .section-services .wp-block-list,
  .services-grid .wp-block-list,
  .section-features .wp-block-list,
  .features-grid .wp-block-list,
  .section-testimonials .wp-block-list,
  .testimonials-grid .wp-block-list,
  .services-grid,
  .features-grid,
  .testimonials-grid {
    grid-template-columns: 1fr;
  }

  .section-stats .stats-grid {
    grid-template-columns: repeat(2, 1fr);
  }

  .section-footer .footer-content {
    grid-template-columns: 1fr;
    text-align: center;
  }

  .about-layout {
    grid-template-columns: 1fr;
    gap: var(--space-lg);
  }

  .contact-layout {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 480px) {
  :root {
    --space-xl: 3rem;
    --space-2xl: 4rem;
    --font-size-base: 16px;
  }

  .section-stats .stats-grid {
    grid-template-columns: 1fr;
  }

  .section-stats .stat-value {
    font-size: 3rem;
  }

  .section-header::after {
    margin-top: var(--space-sm);
  }
}

/* =================================================================
   ACCESSIBILITY
   ================================================================= */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}

/* Focus styles */
a:focus-visible,
button:focus-visible,
input:focus-visible,
textarea:focus-visible,
select:focus-visible,
.wp-block-button__link:focus-visible {
  outline: 3px solid var(--accent-color);
  outline-offset: 3px;
}

/* Skip link */
.skip-link {
  position: absolute;
  top: -100%;
  left: 50%;
  transform: translateX(-50%);
  padding: var(--space-sm) var(--space-md);
  background: var(--accent-color);
  color: white;
  border-radius: var(--border-radius);
  z-index: 9999;
}

.skip-link:focus {
  top: var(--space-sm);
}

/* Screen reader only */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

/* =================================================================
   PRINT STYLES
   ================================================================= */
@media print {
  .section-navigation,
  .section-footer,
  .wp-block-button {
    display: none !important;
  }

  body {
    color: black;
    background: white;
  }

  .section-hero {
    min-height: auto;
    padding: 2rem;
  }

  .wp-block-group {
    padding: 1rem;
  }
}
`;
  }

  /**
   * Convert hex color to RGB values
   */
  private hexToRGB(hex: string): string {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (result) {
      return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`;
    }
    return '139, 92, 246'; // fallback purple
  }

  /**
   * Adjust color brightness
   */
  private adjustColor(hex: string, amount: number): string {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (!result) return hex;

    let r = parseInt(result[1], 16) + amount;
    let g = parseInt(result[2], 16) + amount;
    let b = parseInt(result[3], 16) + amount;

    r = Math.max(0, Math.min(255, r));
    g = Math.max(0, Math.min(255, g));
    b = Math.max(0, Math.min(255, b));

    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
  }
}
