import { Injectable } from '@nestjs/common';
import { SiteSettings } from '@builder/shared';

// Style preset configurations
interface StylePresetConfig {
  fontFamily: string;
  headingWeight: string;
  borderRadius: string;
  shadowIntensity: string;
  backgroundStyle: string;
  buttonStyle: string;
}

const STYLE_PRESETS: Record<string, StylePresetConfig> = {
  modern: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    headingWeight: '700',
    borderRadius: '12px',
    shadowIntensity: '0 10px 40px rgba(0,0,0,0.1)',
    backgroundStyle: 'gradient',
    buttonStyle: 'rounded-gradient',
  },
  classic: {
    fontFamily: "'Georgia', 'Times New Roman', serif",
    headingWeight: '600',
    borderRadius: '4px',
    shadowIntensity: '0 2px 8px rgba(0,0,0,0.08)',
    backgroundStyle: 'solid',
    buttonStyle: 'squared',
  },
  bold: {
    fontFamily: "'Poppins', 'Montserrat', sans-serif",
    headingWeight: '800',
    borderRadius: '0',
    shadowIntensity: '0 20px 60px rgba(0,0,0,0.15)',
    backgroundStyle: 'dark',
    buttonStyle: 'sharp',
  },
  minimal: {
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    headingWeight: '500',
    borderRadius: '2px',
    shadowIntensity: 'none',
    backgroundStyle: 'clean',
    buttonStyle: 'outline',
  },
  playful: {
    fontFamily: "'Nunito', 'Comic Sans MS', cursive",
    headingWeight: '700',
    borderRadius: '24px',
    shadowIntensity: '0 8px 30px rgba(0,0,0,0.12)',
    backgroundStyle: 'colorful',
    buttonStyle: 'pill',
  },
  professional: {
    fontFamily: "'Source Sans Pro', 'Open Sans', sans-serif",
    headingWeight: '600',
    borderRadius: '6px',
    shadowIntensity: '0 4px 16px rgba(0,0,0,0.06)',
    backgroundStyle: 'corporate',
    buttonStyle: 'standard',
  },
};

@Injectable()
export class StylesService {
  /**
   * Generate premium CSS for a WordPress site based on settings
   */
  generatePremiumCSS(settings: SiteSettings): string {
    const preset = STYLE_PRESETS[settings.stylePreset] || STYLE_PRESETS.modern;
    const accentColor = settings.accentColor || '#8B5CF6';
    const accentRGB = this.hexToRGB(accentColor);

    return `
/* =================================================================
   PREMIUM WEBSITE STYLES - Generated by AI Website Builder
   ================================================================= */

/* Import Google Fonts */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Poppins:wght@400;500;600;700;800&family=Nunito:wght@400;600;700&family=Source+Sans+Pro:wght@400;600;700&display=swap');

/* CSS Variables */
:root {
  --accent-color: ${accentColor};
  --accent-rgb: ${accentRGB};
  --accent-light: rgba(${accentRGB}, 0.1);
  --accent-medium: rgba(${accentRGB}, 0.2);
  --font-family: ${preset.fontFamily};
  --heading-weight: ${preset.headingWeight};
  --border-radius: ${preset.borderRadius};
  --shadow: ${preset.shadowIntensity};
  --gradient: linear-gradient(135deg, ${accentColor} 0%, ${this.adjustColor(accentColor, -20)} 100%);
  --gradient-subtle: linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%);
  --text-primary: #0f172a;
  --text-secondary: #475569;
  --text-muted: #94a3b8;
  --background: #ffffff;
  --surface: #f8fafc;
}

/* Base Typography */
body {
  font-family: var(--font-family);
  color: var(--text-primary);
  line-height: 1.7;
  font-size: 17px;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* Headings */
h1, h2, h3, h4, h5, h6,
.wp-block-heading {
  font-family: var(--font-family);
  font-weight: var(--heading-weight);
  line-height: 1.2;
  margin-bottom: 1rem;
  color: var(--text-primary);
}

h1, .wp-block-heading[class*="h1"] {
  font-size: clamp(2.5rem, 5vw, 4rem);
  letter-spacing: -0.02em;
}

h2, .wp-block-heading[class*="h2"] {
  font-size: clamp(2rem, 4vw, 3rem);
  letter-spacing: -0.01em;
}

h3, .wp-block-heading[class*="h3"] {
  font-size: clamp(1.5rem, 3vw, 2rem);
}

p {
  color: var(--text-secondary);
  margin-bottom: 1.5rem;
  font-size: 1.125rem;
  line-height: 1.8;
}

/* =================================================================
   SECTION STYLES
   ================================================================= */

/* Base Section */
.wp-block-group {
  padding: 5rem 2rem;
  position: relative;
}

@media (max-width: 768px) {
  .wp-block-group {
    padding: 3rem 1.5rem;
  }
}

/* Section Inner */
.wp-block-group > * {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}

/* Hero Section */
.section-hero {
  min-height: 85vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  background: linear-gradient(135deg, ${this.adjustColor(accentColor, 40)} 0%, ${this.adjustColor(accentColor, 30)} 50%, #ffffff 100%);
  position: relative;
  overflow: hidden;
  padding: 6rem 2rem;
}

.section-hero::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, rgba(${accentRGB}, 0.1) 0%, transparent 70%);
  animation: pulse-bg 15s ease-in-out infinite;
}

@keyframes pulse-bg {
  0%, 100% { transform: scale(1); opacity: 0.5; }
  50% { transform: scale(1.1); opacity: 0.8; }
}

.section-hero h1 {
  font-size: clamp(2.5rem, 6vw, 4.5rem);
  max-width: 900px;
  margin-bottom: 1.5rem;
  position: relative;
  z-index: 1;
  background: linear-gradient(135deg, var(--text-primary) 0%, var(--accent-color) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.section-hero p {
  font-size: 1.35rem;
  max-width: 650px;
  margin: 0 auto 2.5rem;
  color: var(--text-secondary);
  position: relative;
  z-index: 1;
}

.section-hero .wp-block-image {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 0;
  opacity: 0.15;
}

.section-hero .wp-block-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

/* About Section */
.section-about {
  background: var(--background);
  padding: 6rem 2rem;
}

.section-about h2 {
  text-align: center;
  margin-bottom: 1rem;
}

.section-about h2 + p {
  text-align: center;
  max-width: 700px;
  margin-left: auto;
  margin-right: auto;
  font-size: 1.2rem;
}

.section-about .wp-block-image {
  margin: 3rem auto;
  max-width: 800px;
  border-radius: var(--border-radius);
  overflow: hidden;
  box-shadow: var(--shadow);
}

.section-about .wp-block-image img {
  width: 100%;
  height: auto;
  display: block;
  transition: transform 0.5s ease;
}

.section-about .wp-block-image:hover img {
  transform: scale(1.02);
}

/* Services Section */
.section-services {
  background: var(--gradient-subtle);
  padding: 6rem 2rem;
}

.section-services h2 {
  text-align: center;
  margin-bottom: 3rem;
}

.section-services .wp-block-list {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 2rem;
  list-style: none;
  padding: 0;
  margin: 0;
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}

.section-services .wp-block-list li {
  background: var(--background);
  padding: 2.5rem;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow);
  transition: all 0.3s ease;
  border: 1px solid rgba(0,0,0,0.05);
  position: relative;
  overflow: hidden;
}

.section-services .wp-block-list li::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 4px;
  height: 100%;
  background: var(--gradient);
  opacity: 0;
  transition: opacity 0.3s ease;
}

.section-services .wp-block-list li:hover {
  transform: translateY(-5px);
  box-shadow: 0 20px 60px rgba(0,0,0,0.12);
}

.section-services .wp-block-list li:hover::before {
  opacity: 1;
}

.section-services .wp-block-list li strong {
  display: block;
  font-size: 1.35rem;
  margin-bottom: 0.75rem;
  color: var(--text-primary);
  font-weight: var(--heading-weight);
}

/* Testimonials Section */
.section-testimonials {
  background: var(--background);
  padding: 6rem 2rem;
}

.section-testimonials h2 {
  text-align: center;
  margin-bottom: 3rem;
}

.section-testimonials .wp-block-list {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
  gap: 2rem;
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}

.section-testimonials .wp-block-list li {
  background: var(--surface);
  padding: 2.5rem;
  border-radius: var(--border-radius);
  position: relative;
  border: 1px solid rgba(0,0,0,0.05);
}

.section-testimonials .wp-block-list li::before {
  content: '"';
  font-size: 5rem;
  color: var(--accent-light);
  position: absolute;
  top: 1rem;
  left: 1.5rem;
  line-height: 1;
  font-family: Georgia, serif;
}

.section-testimonials .wp-block-list li strong {
  display: block;
  margin-top: 1.5rem;
  color: var(--accent-color);
  font-weight: 600;
}

/* Contact Section */
.section-contact {
  background: linear-gradient(135deg, var(--text-primary) 0%, ${this.adjustColor(accentColor, -40)} 100%);
  color: white;
  padding: 6rem 2rem;
  text-align: center;
}

.section-contact h2 {
  color: white;
  margin-bottom: 1.5rem;
}

.section-contact p {
  color: rgba(255,255,255,0.85);
  font-size: 1.2rem;
}

.section-contact a {
  color: white;
}

/* Footer Section */
.section-footer {
  background: var(--text-primary);
  color: var(--text-muted);
  padding: 3rem 2rem;
  text-align: center;
}

.section-footer p,
.section-footer small {
  color: var(--text-muted);
  font-size: 0.95rem;
  margin: 0;
}

/* =================================================================
   BUTTON STYLES
   ================================================================= */

.wp-block-button {
  margin: 1rem 0;
}

.wp-block-button__link,
.wp-element-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 1rem 2.5rem;
  font-size: 1.1rem;
  font-weight: 600;
  text-decoration: none;
  border-radius: var(--border-radius);
  transition: all 0.3s ease;
  cursor: pointer;
  border: none;
  background: var(--gradient);
  color: white !important;
  box-shadow: 0 4px 15px rgba(${accentRGB}, 0.4);
  position: relative;
  overflow: hidden;
}

.wp-block-button__link::before {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);
  transition: left 0.5s ease;
}

.wp-block-button__link:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(${accentRGB}, 0.5);
}

.wp-block-button__link:hover::before {
  left: 100%;
}

/* Contact Section Buttons */
.section-contact .wp-block-button__link {
  background: white;
  color: var(--accent-color) !important;
  box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}

.section-contact .wp-block-button__link:hover {
  background: var(--surface);
  transform: translateY(-2px);
}

/* =================================================================
   IMAGE STYLES
   ================================================================= */

.wp-block-image {
  margin: 2rem 0;
}

.wp-block-image img {
  max-width: 100%;
  height: auto;
  border-radius: var(--border-radius);
}

.wp-block-image.alignfull img {
  border-radius: 0;
}

/* =================================================================
   RESPONSIVE DESIGN
   ================================================================= */

@media (max-width: 768px) {
  .section-hero {
    min-height: auto;
    padding: 4rem 1.5rem;
  }

  .section-hero h1 {
    font-size: 2.25rem;
  }

  .section-hero p {
    font-size: 1.1rem;
  }

  .section-services .wp-block-list,
  .section-testimonials .wp-block-list {
    grid-template-columns: 1fr;
  }

  .section-services .wp-block-list li,
  .section-testimonials .wp-block-list li {
    padding: 2rem;
  }
}

/* =================================================================
   ANIMATIONS
   ================================================================= */

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.wp-block-group > * {
  animation: fadeInUp 0.6s ease-out forwards;
}

/* Stagger animations */
.wp-block-group > *:nth-child(1) { animation-delay: 0.1s; }
.wp-block-group > *:nth-child(2) { animation-delay: 0.2s; }
.wp-block-group > *:nth-child(3) { animation-delay: 0.3s; }
.wp-block-group > *:nth-child(4) { animation-delay: 0.4s; }
.wp-block-group > *:nth-child(5) { animation-delay: 0.5s; }

/* =================================================================
   ACCESSIBILITY
   ================================================================= */

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}

/* Focus styles */
a:focus,
button:focus,
.wp-block-button__link:focus {
  outline: 2px solid var(--accent-color);
  outline-offset: 2px;
}
`;
  }

  /**
   * Convert hex color to RGB values
   */
  private hexToRGB(hex: string): string {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (result) {
      return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`;
    }
    return '139, 92, 246'; // fallback purple
  }

  /**
   * Adjust color brightness
   */
  private adjustColor(hex: string, amount: number): string {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (!result) return hex;

    let r = parseInt(result[1], 16) + amount;
    let g = parseInt(result[2], 16) + amount;
    let b = parseInt(result[3], 16) + amount;

    r = Math.max(0, Math.min(255, r));
    g = Math.max(0, Math.min(255, g));
    b = Math.max(0, Math.min(255, b));

    return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
  }
}
